### PR TITLE
Allow single letter mixins

### PR DESCRIPTION
**Pull request by JakeChampion**
If an origami component has a single letter name, then it's primary mixin would be a single letter
E.G. The component `@financial-times/a` would have a primary mixin named `a`.

I came across this when testing out a new version of `obt init` and I set the component name to `a`.

I'm not sure if we want this functionality, maybe we want to disallow single letter component names instead?

Below is a copy of the commands I ran - I used the create-origami-component spec v2 branch and obt v11:
```
❯ ./bin/run
? component name (required) a
? Should we create this component in the current directory, or a subdirectory? ./a
? description (required) a
? keywords (to help discoverability in the registry) a
? component category (https://origami.ft.com/spec/v1/manifest/#origamicategory) components
? supported brands (https://origami.ft.com/docs/components/branding/) master, internal, whitelabel
? will your component use JavaScript? (this will add some helpful Origami JavaScript boilerplate) Yes
? will your component use Sass? (this will add some helpful Origami Sass boilerplate) Yes
? support status (https://origami.ft.com/spec/v1/manifest/#supportstatus) experimental
? support team email (required) origami.support@ft.com
? support team slack channel (required) #origami-support
? support Github team (required) origami-core

=== Your component: ===
{
  name: 'a',
  path: './a',
  description: 'a',
  keywords: [ 'a' ],
  category: 'components',
  brands: [ 'master', 'internal', 'whitelabel' ],
  javascript: true,
  scss: true,
  status: 'experimental',
  email: 'origami.support@ft.com',
  slack: '#origami-support',
  githubTeam: 'origami-core'
}
===================

? is this right? Yes
ok! generating 'a' into './a'
... 
yay! 'a' is ready!
❯ cd a
❯ obt i
 ❯ Installing NPM components
 ✔ Installing NPM components
   ✔ Starting NPM
❯ obt v
 ✔ Verifying your origami.json
 ✔ Verifying your package.json
 ✔ Verifying your component's README.md
 ✔ Linting Javascript
 ✖ Linting Sass
   → Failed linting: 
     ./main.scss:13:1 error - Expected @mixin name to match specified pattern (scss/at-mixin-pattern)
```

### CODE REVIEW

**Comment by chee** [comment]
Maybe we'll want to do is make this more strict:
https://origami.ft.com/spec/v1/components/#naming-conventions

> Components must be named using a short descriptive term (hyphenated if necessary) and should be prefixed with o- (for Origami). The name must only contain lower-case ASCII letters, and hyphens. This name must be used as the repository name, the name property in origami.json and as a prefix for any default CSS class names.

> If a component is not maintained by the Origami team, then it may be prefixed with a different letter than o-, E.g. n-button, g-audio. This practice is discouraged, it’s preferred that authors specify a support contact other than Origami in the component manifest.

For example, I'm up for us straight up saying component names **must** begin with `o-`

**Comment by notlee** [comment]
I'm good with requiring o-. We'd need to rename ftdomdelegate though, there might be others

**Comment by JakeChampion** [comment]
Okay, I'll update the spec to require `o-` prefix for `component`s 👍 

@notlee I think ftdomdelegate should not be listed as a `component`, it doesn't abide by the component spec and it is more akin to ft-date-format, which is a `library` and not a `component`.

What do you both think about changing ftdomdelegate to `library`?
https://github.com/Financial-Times/ftdomdelegate/blob/f759caef06dc94731b8ddd53ab93a2412b3b83d7/origami.json#L4

https://github.com/Financial-Times/ft-date-format/blob/9a415d45e6f8002691b7634c8e88d9db78c92ecd/origami.json#L3

**Comment by chee** [comment]
> Okay, I'll update the spec to require `o-` prefix for `component`s +1
> 
> @notlee I think ftdomdelegate should not be listed as a `component`, it doesn't abide by the component spec and it is more akin to ft-date-format, which is a `library` and not a `component`.
> 
> What do you both think about changing ftdomdelegate to `library`?
> [Financial-Times/ftdomdelegate@`f759cae`/origami.json#L4](https://github.com/Financial-Times/ftdomdelegate/blob/f759caef06dc94731b8ddd53ab93a2412b3b83d7/origami.json#L4)
> 
> [Financial-Times/ft-date-format@`9a415d4`/origami.json#L3](https://github.com/Financial-Times/ft-date-format/blob/9a415d45e6f8002691b7634c8e88d9db78c92ecd/origami.json#L3)

yes, i think ftdomdelegate might be a library.

**Comment by notlee** [comment]
@JakeChampion Good shout, I think ftdomdelegate makes sense as a library. Except...

1. Can libraries be included via v3 of the Build Service? I wonder if that will impact any projects and make migration more difficult (thinking of other libraries too)

2. There are other components we would need to rename. Because of the naming convention part of the spec we'd need to update Sass, class names, etc, which projects will need to change to migrate. There are only a few but I'm hesitant to add more work to the major cascade. We don't want to reinforce them being painful. I'd prefer we spec "[a-z]-whatever" or leave it as is as part of the npm migration.
    - n-alert-banner (actually deprecated, incorrect status)
    - g-audio (unsure if this is used?)
    - ftdomdelegate (library?)
    - n-notification (in production)
    - n-sliding-popup (in production)

**Comment by chee** [comment]
> @JakeChampion Good shout, I think ftdomdelegate makes sense as a library. Except...
> 
>     1. Can libraries be included via v3 of the Build Service? I wonder if that will impact any projects and make migration more difficult (thinking of other libraries too)
> 
>     2. There are other components we would need to rename. Because of the naming convention part of the spec we'd need to update Sass, class names, etc, which projects will need to change to migrate. There are only a few but I'm hesitant to add more work to the major cascade. We don't want to reinforce them being painful. I'd prefer we spec "[a-z]-whatever" or leave it as is as part of the npm migration.
>        
>        * n-alert-banner (actually deprecated, incorrect status)
>        * g-audio (unsure if this is used?)
>        * ftdomdelegate (library?)
>        * n-notification (in production)
>        * n-sliding-popup (in production)


Aren't we talking about making `o-` required as part of **v2**? that's what i've been talking about.

**Comment by notlee** [comment]
>There are other components we would need to rename. Because of the naming convention part of the spec we'd need to update Sass, class names, etc, which projects will need to change to migrate. There are only a few but I'm hesitant to add more work to the major cascade. We don't want to reinforce them being painful. I'd prefer we spec "[a-z]-whatever" or leave it as is as part of the npm migration.

Yeah, those are Origami components (not maintained by our team) that will need to up updated to spec v2

**Comment by notlee** [comment]
>Can libraries be included via v3 of the Build Service? I wonder if that will impact any projects and make migration more difficult (thinking of other libraries too)

And this question is tangential

**Comment by JakeChampion** [comment]
> Can libraries be included via v3 of the Build Service? I wonder if that will impact any projects and make migration more difficult (thinking of other libraries too)

Libraries can be included via v3 of build service, yes 👍

**Comment by chee** [comment]
the maintainers of `g-audio`, `n-notification` and `n-sliding-popup` can choose to:
- rename them as part of becoming a **v2** component
- leave them as **v1** components forever
- choose to break with the spec on this point

on that third option, of breaking with the spec:

- n-sliding-popup has no silent mode, no primary mixin, 
- g-audio has no silent mode, no primary mixin

the spec says the repo name must [match the `name` property in the `origami.json`](https://origami.ft.com/spec/v1/components/#naming-conventions)

there's literally not a single spec compliant origami component in existence

we want as few branches as possible in the v2 spec

**Comment by notlee** [comment]
>rename them as part of becoming a v2 component

That would be great but isn't a small amount of work to add to the major cascade, it introduces more opportunities for regression.

>leave them as v1 components forever

That could work. I don't think there's much of an issue including two versions of low level components, one via bower one via npm, in this limited case. Projects which depend on it will need to maintain Bower support and that will complicate the migration plan for customer products.

>choose to break with the spec on this point
>n-sliding-popup has no silent mode, no primary mixin,

Hah good point. We've improved validation in our tooling, will they be able to break with the spec here and still be maintained with obt? They will need a primary mixin, which can be added quite straightforwardly without requiring CSS/template refactoring.

>we want as few branches as possible in the v2 spec

Not changing the spec here and allowing a component named `a` doesn't change the number of branches in the spec and doesn't increase the scope of the major cascade. Anyhow, if we want to make `o-` a requirement we can do spec v3?

**Comment by JakeChampion** [comment]
I'd be tempted to say we have `o-` prefix as a *must* for v2.0 and we can downgrade from a *must* to a *should* in v2.1 if that is what our users would want

**Comment by notlee** [comment]
Hmm I still think if we want to make the naming convention more strict this should come later. I don't think we should make more work for ourselves and our users because we wouldn't like a component named `a`. Especially not when what we've communicated is work to replace bower with npm. The proposal to drop silent mode and rename master brand is already pushing the scope of the migration work, although I'd argue with more tangible benefits.

If we want to reduce the complexity of the spec though we could make this:

>Components must be named using a short descriptive term (hyphenated if necessary) and should be prefixed with o- (for Origami). The name must only contain lower-case ASCII letters, and hyphens. This name must be used as the repository name, the name property in origami.json and as a prefix for any default CSS class names.
>
>If a component is not maintained by the Origami team, then it may be prefixed with a different letter than o-, E.g. n-button, g-audio. This practice is discouraged, it’s preferred that authors specify a support contact other than Origami in the component manifest.

This:

>Components must be named using a short descriptive term. The name must only contain lower-case ASCII letters, and hyphens. This name must be used as the repository name, the name property in origami.json and as a prefix for any default CSS class names.

**Comment by chee** [comment]
> I don't think we should make more work for ourselves and our users because we wouldn't like a component named `a`. 

Don't be glib.

> Components must be named using a short descriptive term. The name must only contain lower-case ASCII letters, and hyphens. This name must be used as the repository name, the name property in origami.json and as a prefix for any default CSS class names.

This seems fine. Note: There _is no name property in origami.json_.

**Comment by JakeChampion** [comment]
A possible side-benefit to requiring the `o-` prefix, is it could make identifying components easier as we could search for npm packages with that prefix.

Below is an example of that via the npm cli:
```
>npm search @financial-times/o-
NAME                      | DESCRIPTION          | AUTHOR          | DATE       | VERSION  | KEYWORDS
@financial-times/o-ads    | This package…        | =briggsc…       | 2021-02-16 | 19.0.1   | origami component ft
@financial-times/o-typogr | Typographical…       | =briggsc…       | 2021-04-06 | 6.4.6    | origami component ft
aphy                      |                      |                 |            |          |
@financial-times/o-grid   | A 12 column…         | =briggsc…       | 2021-03-02 | 5.2.10   | origami component ft
@financial-times/o-spacin | o-spacing…           | =alexwilson…    | 2020-11-17 | 2.1.0    | origami component ft
g                         |                      |                 |            |          |
@financial-times/o-icons  | Helper Sass for the… | =briggsc…       | 2021-03-25 | 6.3.0    | origami component ft
@financial-times/o-expand | Accessible,…         | =alexwilson…    | 2020-11-20 | 5.0.11   | origami component ft
er                        |                      |                 |            |          |
@financial-times/o-colors | A component to…      | =briggsc…       | 2021-01-04 | 5.3.1    | origami component ft
@financial-times/o-button | o-buttons provides…  | =alexwilson…    | 2020-11-30 | 6.2.0    | origami component ft
s                         |                      |                 |            |          |
@financial-times/o-normal | Foundation styles…   | =alexwilson…    | 2020-11-10 | 2.0.7    | origami component ft
ise                       |                      |                 |            |          |
@financial-times/o-tracki | Origami module for…  | =briggsc…       | 2021-04-07 | 3.1.0    | origami component ft
ng                        |                      |                 |            |          |
@financial-times/o-video  | Video player for…    | =briggsc…       | 2021-02-04 | 6.1.3    | origami component ft
@financial-times/o-messag | Product messaging…   | =briggsc…       | 2021-03-16 | 4.2.6    | origami component ft
e                         |                      |                 |            |          |
@financial-times/o-test-c | A component used to… | =briggsc…       | 2021-03-22 | 2.1.16   |
omponent                  |                      |                 |            |          |
@financial-times/o-fonts  | _Use `o-fonts` to…   | =briggsc…       | 2021-04-06 | 4.5.0    | origami component ft
@financial-times/o-visual | This…                | =alexwilson…    | 2020-11-16 | 3.0.6    | origami component ft
-effects                  |                      |                 |            |          |
@financial-times/o-editor | o-editorial-typogra… | =alexwilson…    | 2020-10-08 | 1.1.0    | origami component ft
ial-typography            |                      |                 |            |          |
@financial-times/o-assets | _Deprecated._…       | =briggsc…       | 2021-01-14 | 3.4.9    | origami component ft
@financial-times/o-overla | Configurable custom… | =alexwilson…    | 2020-12-08 | 3.1.0    | origami component ft
y                         |                      |                 |            |          |
@financial-times/o-layout | A layout component…  | =briggsc…       | 2021-03-16 | 4.3.0    | origami component ft
```

**Comment by JakeChampion** [comment]
>The proposal to drop silent mode and rename master brand is already pushing the scope of the migration work

Dropping silent mode can be done as a minor update on the spec because it would change from a *must* to a *should*

Renaming master brand can be done in a backwards-compatible way to allow the change to be a minor update on the spec as well. I.E. We could state "master" is a deprecated alias for "pink"

Changing the component name requirements from a *should* to a *must* is a major update on the spec because it could make some currently spec conforming components become spec non-conforming, such as the ones previously listed (g-audio etc).

I did miss the fact that a name change would also require updates to markup/templates due to the class name also having to be updated.

@chee and @notlee, if we spoke to the maintainers of those components and they agreed to change their name as part of the bower to npm migration, would that make this acceptable to include in spec 2.0?

**Comment by notlee** [comment]
>Don't be glib.

Sorry, I was being a bit glib. 

>Dropping silent mode can be done as a minor update on the spec because it would change from a must to a should

The benefits of dropping silent mode come from it no longer being used (no Origami maintained components document the silent mode mixin in the readme, all include a primary mixin already). It would be great to remove it from the spec and our components entirely in v2. That's probably a conversion for [over on the remove silent mode variable proposal](https://github.com/Financial-Times/origami/pull/121) though. :) 

>Renaming master brand can be done in a backwards-compatible way to allow the change to be a minor update on the spec as well. I.E. We could state "master" is a deprecated alias for "pink"

That's true. Let's see how the conversation goes with design. If we're able to agree on the rename quickly before v2 components are released it would be worth spiking to see how much work a post-v2 alias would be vs. doing it as part of v2. (Here's the [master brand rename proposal](https://github.com/Financial-Times/origami/pull/65) for reference.)

>I did miss the fact that a name change would also require updates to markup/templates due to the class name also having to be updated.
>
>@chee and @notlee, if we spoke to the maintainers of those components and they agreed to change their name as part of the bower to npm migration, would that make this acceptable to include in spec 2.0?

Yeah I'm super keen to avoid bloating the migration work (beyond small find-replace tasks, that are unlikely to introduce unnoticed regressions). We found markup updates the most painful in the last major cascade. 

It would be great to have a proper proposal, like you suggested friday, with benefits, alternatives, etc. If we do want to include the work speaking to the maintainers and a delivery lead would be good :) If this cascade goes ~smoothly~ as planned, hopefully people will be less scared of future cascades

**Comment by notlee** [comment]
Hi Jake, you asked me to comment on a pull request you've opened to test a Slack integration

**Review by notlee — APPROVED** [review]
This meets the naming requirements we discussed as part of drafting v2 of the specification. It's a bad name but not a wrong name! :shipit:

**Pull request merged**
